defmodule Bella.Repo.Migrations.CreateBookingsTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:bookings, primary_key: false) do
      add(:id, :bigserial, null: false, primary_key: true)
      add(:start, :naive_datetime, null: false)
      add(:duration, :bigint, null: false)
      add(:user_id, :bigint, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    execute("""
    ALTER TABLE bookings
    ADD CONSTRAINT bookings_cannot_overlap
    EXCLUDE USING gist (
      box(
        point(
          extract( epoch from start ), user_id
        ),
        point(
          extract( epoch from start ) + duration - 1,
          user_id + 0.5
        )
      )
      WITH &&
    )
    """)
  end

  def down do
    execute("""
    ALTER TABLE bookings
    DROP CONSTRAINT bookings_cannot_overlap
    """)

    drop(table(:bookings))
  end
end
